project: 
  type: website

website: 
  page-navigation: true
  title: "SFSU Acoustic Ecology" 
  site-url: "https://asimonis.github.io/SFSUAcousticEcology/" 
  repo-url: "https://github.com/asimonis/SFSUAcousticEcology/"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  search: true
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: "https://commons.wikimedia.org/wiki/File:San_Francisco_State_Gators_logo.svg"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://asimonis.github.io/SFSUAcousticEcology/
        text: "SFSU Acoustic Ecology"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: content/SharedValues.qmd
        text: Shared Values and Best Practices
      - href: content/PublicationsPresentations.qmd
        text: Publications and Presentations
      - section: "Open Science"
        contents: 
        - href: content/Getting-Started.qmd
          text: Getting Started
        - href: content/Stack-Exchange.qmd
          text: Stack Exchange
        - href: content/ResearchGuide.qmd
          text: Research Guide
        - href: content/WritingGuide.qmd
          text: Writing Guide
        - href: content/Zotero.qmd
          text: Zotero
        
format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
