---
title: Shared Values
---

# **Shared Values & Best Practices**

## **Note**

This is a living document which shall always be considered a "draft," as incoming and veteran members of the lab may want to contribute ideas or revisions. This is a place to begin, a place to return to, a place to ground ongoing conversations.

## **Lab Values**

We value fair treatment of all members and try to create a safe and collaborative atmosphere. We are dedicated to providing an environment that cultivates and celebrates individual differences and recognizes these differences as integral to the scientific enterprise. We welcome members and collaborators of marginalized groups of all kinds, including but not limited to those based on race, color, physical appearance, gender identity and expression, nationality or ethnicity, sex, sexual orientation, religion, genetic characteristics, neurodiversity, disability, age, ancestry, marital status, family status, veteran status, socioeconomic status, or immigration status. We recognize that success in science requires an environment where all people feel secure in their personal identities.

The SF Acoustic Ecology Lab Values also include:

-   Ethics, justice, and equity for research participants and researchers
-   Communication and respect
-   Open data and methods
-   Willingness to teach and learn
-   Openness to fresh perspectives
-   Effective mentoring as a way to increase access, equity and inclusion in STEAMM (**S**cience, **T**echnology, **E**ngineering, **A**rt, **M**athematics & **M**edicine)
-   Bringing your whole self, or as much as you want to bring, to the lab

## **Best Practices**

### **Communication**

1.  We hold lab meetings regularly in which all members are expected to attend. During these meetings all members are expected to contribute by sharing progress reports, discussing challenges, and celebrating successes.
2.  We use Slack and email for informal discussions between lab members and project teams. Similarly, we use Slack and Trello for some projects with external collaborators.
3.  All lab members are expected to check & respond to email and Slack regularly

### **Collaboration**

1.  Lab members and collaborators, including students, interns, volunteers, and other mentees, can expect respect, patience, and learning opportunities from each other.
2.  Collaborators are expected to be in regular communication with each other.
3.  At the onset of a project, collaborators should discuss their expectations for the project and of each other, and establish a feedback system to evaluate progress along the way. Acknowledgements and co-authorship agreements are discussed early and often. 
4.  Collaborators are encouraged to ask questions and seek understanding from each other.

### **Safety**

1.  Lab members are expected to follow all safety protocols. If they are not sure of the protocol, then they should request this information.
2.  Lab members should never feel obligated to perform a task that they do not feel is safe.
3.  Lab members are encouraged to speak up if they feel they need training to perform a specific task safely.
4.  If lab members have a safety concern, they should bring it up with the PI, EOS Safety Coordinator (Brita Larsson), or the other lab members.
5.  If a lab member feels their safety concerns are not being taken seriously, they can consult [SFSU Environment, Health, and Safety (EHS)](https://ehs.sfsu.edu/). Email: [sfehs\@sfsu.edu](mailto:sfehs@sfsu.edu); Telephone: (415) 338-2565

### **Handling or resolving incivility, harassment, or assault**

1.  Maintaining a positive lab culture requires efforts from our entire research group. We expect all lab members:

    -   To familiarize themselves with the definitions of incivility, microaggressions, harassment, and assault, and refrain from these behaviors.
    -   To use safe, responsive, and effective ways to respond to cases of incivility, harassment, and/or assault that they observe or learn of from a lab member.
    -   To offer support to those who have been harmed.
    -   To make it possible for those who have been harmed to return to normalcy and/or work as soon as they wish. Alternatively, depending on the wishes of the person who has been harmed, to create opportunities for rest or leave from work or school.

2.  Lab members should consider resolving conflicts with each other through empathetic but direct conversation.

3.  If someone is not comfortable discussing an issue with the lab member who caused them harm, they can bring it up with the PI to mediate a conversation. If they do not feel comfortable interacting with the person who has harmed them they may contact the PI (Ellen Hines, ehines\@sfsu.edu, or Anne Simonis, asimonis\@sfsu.edu), and if they are not comfortable discussing with the PI, they may also contact the EOS safety officer (Brita Larssen, [blarssen\@sfsu.edu](mailto:blarssen@sfsu.edu)), the EOS director (Kathy Boyer, [kboyer\@sfsu.edu](mailto:kboyer@sfsu.edu)), or seek advice from the university ombuds (<https://www.sfsu.edu/university-ombuds>).

4.  SF State and EOS fosters a campus free of sexual violence including sexual harassment, domestic violence, dating violence, stalking, and/or any form of sex or gender discrimination. If you disclose a personal experience as an SF State student, the PI or faculty member is required to notify the Dean of Students. As mandatory reporters, PIs and faculty members must report any child abuse and neglect whenever, in their professional capacity or within the scope of their employment, they have knowledge of, observe, or reasonably suspect it. 

To disclose any such violence confidentially, contact:

-   The SAFE Place: [The SAFE Place \| Dean of Students (DOS)](https://dos.sfsu.edu/safeplace) or (415) 338-2208
-   Counseling and Psychological Services Center: <https://psyservs.sfsu.edu/> or  (415) 338-2208
-   For more information on your rights and available resources, please see: Equity Programs & Compliance at <https://titleix.sfsu.edu/> 

Acts of incivility, harassment, or assault within our lab group will lead to swift sanctions for the person who has caused harm, up to and including expulsion from the laboratory group depending on the wishes of the person who was harmed, and the severity of the act.\

### **Additional Resources for Support and Learning:**

1.  Learning and Academic Support

-   To chat or make an appointment with a librarian to focus on your research needs:<https://library.sfsu.edu/research-help> 
-   For timelines, thesis formatting, FAQ about graduate programs: <https://grad.sfsu.edu/content/thesis-dissertation-guidelines> 

2.  Support for Well-Being and Inclusion

-   Any student who has difficulty accessing sufficient food to eat every day, or who lacks a safe and stable place to live is encouraged to contact: [basicneeds\@sfsu.edu](mailto:basicneeds@sfsu.edu) or (415) 338-1203 or visit <https://basicneeds.sfsu.edu/> 
-   For confidential counseling and consultations for psychiatric service and mental health programming: <https://psyservs.sfsu.edu/> 
-   For support for students with disabilities and accessibility across campus: <https://access.sfsu.edu/> 
-   For on-campus childcare for children of SF State employees, students, and the community: <https://childrenscampus.sfsu.edu/> 
-   Responsible for leading, coordinating, implementing and evaluating programs to support diversity, equity and inclusion: [equity\@sfsu.edu](mailto:equity@sfsu.edu) or (415) 338-7290 or visit <https://equity.sfsu.edu/> 
-   For student organizations, clubs, service opportunities, and many other ways to connect with others on campus: <https://activities.sfsu.edu/> 
-   For programs and services are designed to help students overcome obstacles that arise from their immigration status and support them through personal and academic excellence: <https://drc.sfsu.edu/> 

3.  Health and Well-Being

-   Students may experience stressors that can impact both their academic experience and personal well-being. If you are experiencing concerns, seeking help is a courageous thing to do for yourself and those who care about you. If the source of your stressors is academic, please contact your PI or a trusted professor or faculty member so that we can find solutions together. For personal concerns, SFSU provides many resources, some of which are listed on the <https://wellness.sfsu.edu/resources> website.
-   National Suicide & Crisis Hotlines:
    -   1-800-SUICIDE or 1-800-784-2433
    -   1-800-273-Talk or 1-800-273-8255
    -   TTY: 1-800-799-4TTY (4889)
